### PR TITLE
fix powerhal crashes

### PR DESCRIPTION
**Pull request by keepcalm444**
Change-Id: I73ddbfa168c918ccd1d96087c40d4715a2403e8a

### CODE REVIEW

**Comment by zwliew** [comment]
The auto brightness adjustment commit is obsolete

**Comment by keepcalm444** [comment]
Ah, ok

**Comment by zwliew** [comment]
BTW are u using this rebated device and kernel trees locally?

**Comment by keepcalm444** [comment]
I am, it's running much better than current CM stuff

**Comment by zwliew** [comment]
Under what conditions does the backlight turn off? When the ambient light is low (nighttime etc)?

Also have you experienced any instabilities with these trees compared to current cm?

**Comment by keepcalm444** [comment]
CABC on, turn the brightness slider all the way down and release the screen. Current ambient brightness is ~1 lux, so pretty dim.

I haven't experienced any reboots, can't recall noticing any jank. As I said, IMO it's running way better than current CM is.

**Comment by zwliew** [comment]
Then seems like the change made [here](https://github.com/zwliew/android_kernel_asus_flo/commit/eaf23cd18529c0d6c3a29cbe56272ca4ab1f82e0) doesn't work.

I'll remerge the overlay change for now. Ideally however, we want to get rid of the overlay change since it actually increases the minimum brightness quite noticeably in dark ambient conditions.

**Comment by zwliew** [comment]
Have you verified that the PowerHAL change works fine? I am unable to test since I kinda broke my flo.

**Comment by zwliew** [comment]
Merged.

**Comment by keepcalm444** [comment]
I don't think it does - it looks like set_profile isn't being called after bootup

I (tried to) switch profile a few times from about 22:05, here's  `adb logcat | grep PowerHAL`:
```
02-23 22:03:35.731   583   583 I PowerHAL: power_init
02-23 22:03:35.732   583   583 D PowerHAL: power_set_interactive ON
02-23 22:03:35.732   583   583 E PowerHAL: sync_thread: failed to send: No such file or directory
02-23 22:03:35.732   583   583 E PowerHAL: touch_boost: failed to send: No such file or directory
02-23 22:03:58.188   583   671 V PowerHAL: set_power_profile: profile=1
02-23 22:03:58.188   583   671 D PowerHAL: set_power_profile: set balanced mode
02-23 22:04:00.222   212   887 E PowerHAL: sync_thread: failed to send: No such file or directory
02-23 22:04:00.222   212   887 E PowerHAL: enc_boost: failed to send: No such file or directory
02-23 22:04:00.394   212   887 E PowerHAL: sync_thread: failed to send: No such file or directory
02-23 22:04:00.394   212   887 E PowerHAL: enc_boost: failed to send: No such file or directory
02-23 22:04:01.074   212   887 E PowerHAL: sync_thread: failed to send: No such file or directory
02-23 22:04:01.074   212   887 E PowerHAL: enc_boost: failed to send: No such file or directory
02-23 22:04:01.420   212   887 E PowerHAL: sync_thread: failed to send: No such file or directory
02-23 22:04:01.420   212   887 E PowerHAL: enc_boost: failed to send: No such file or directory
02-23 22:04:14.174   583   695 D PowerHAL: power_set_interactive OFF
02-23 22:04:15.306   583   695 D PowerHAL: power_set_interactive ON
02-23 22:05:30.525   583   695 D PowerHAL: power_set_interactive OFF
02-23 22:05:41.980   583   695 D PowerHAL: power_set_interactive ON
02-23 22:06:14.295   583   695 D PowerHAL: power_set_interactive OFF
02-23 22:07:24.836   583   695 D PowerHAL: power_set_interactive ON
02-23 22:08:04.584   583   695 D PowerHAL: power_set_interactive OFF
```

And here's the limited_max/min_cpu nodes:
```
root@flo:/sys/kernel/cpufreq_limit # cat limited_max_freq                                                                                                                                                          
4294967295
root@flo:/sys/kernel/cpufreq_limit # cat limited_min_freq                                                                                                                                                          
4294967295
```
(echoing values manually to these nodes seems to work)

**Comment by zwliew** [comment]
Does this commit actually fix crashes? I don't remember seeing any crashes when I last used wrote it as a string (sysfs_write()).

**Comment by keepcalm444** [comment]
Yeah, my flo wouldn't boot before this (strlen doesn't like being given ints)

**Pull request closed without merging**
